# Generated by Django 4.2.4 on 2025-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discharge_rate', models.IntegerField(verbose_name='Расход энергии')),
                ('image', models.CharField(max_length=255, verbose_name='Изображение')),
                ('price', models.CharField(max_length=255, verbose_name='Ценовая категория')),
                ('power_multiplier', models.FloatField(verbose_name='Множитель мощности')),
            ],
        ),
    ]
