# Generated by Django 4.2.4 on 2025-09-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_moderated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discharge_rate', models.IntegerField(verbose_name='Расход энергии')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение')),
                ('price', models.CharField(max_length=255, verbose_name='Ценовая категория')),
                ('power_multiplier', models.FloatField(verbose_name='Множитель мощности')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги в заявке')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='Расчётное время (мин)')),
                ('drone_weight', models.FloatField(blank=True, null=True, verbose_name='Масса дрона (кг)')),
                ('cargo_weight', models.FloatField(blank=True, null=True, verbose_name='Масса груза (кг)')),
                ('battery_capacity', models.IntegerField(blank=True, null=True, verbose_name='Ёмкость аккумулятора (mAh)')),
                ('battery_voltage', models.FloatField(blank=True, null=True, verbose_name='Напряжение батареи (V)')),
                ('efficiency', models.FloatField(blank=True, null=True, verbose_name='КПД')),
                ('battery_remaining', models.FloatField(blank=True, null=True, verbose_name='Остаток заряда (%)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='application.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='application.service')),
            ],
            options={
                'unique_together': {('order', 'service')},
            },
        ),
    ]
