# Generated by Django 4.2.4 on 2025-09-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='category',
        ),
    ]
