# Generated by Django 4.2.4 on 2025-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_price_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='battery_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ёмкость аккумулятора (mAh)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='runtime',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчётное время (мин)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='discharge_rate',
            field=models.FloatField(verbose_name='Расход энергии'),
        ),
    ]
