# Generated by Django 4.2.4 on 2025-09-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_orderitem_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='discharge_rate',
        ),
    ]
