# Generated by Django 4.2.4 on 2025-09-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_orderitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
