# Generated by Django 4.2.4 on 2025-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_order_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='battery_remaining',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='battery_voltage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cargo_weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drone_weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='efficiency',
        ),
        migrations.AddField(
            model_name='order',
            name='battery_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ёмкость аккумулятора (mAh)'),
        ),
        migrations.AddField(
            model_name='order',
            name='battery_remaining',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаток заряда (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Напряжение батареи (V)'),
        ),
        migrations.AddField(
            model_name='order',
            name='cargo_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса груза (кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='drone_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса дрона (кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='КПД'),
        ),
    ]
