# Generated by Django 4.2.4 on 2025-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_dronemode_droneorder_droneorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronemode',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
