# Generated by Django 4.2.4 on 2025-09-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_alter_dronemode_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneorder',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_moderated', to=settings.AUTH_USER_MODEL),
        ),
    ]
