# Generated by Django 4.2.4 on 2025-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_droneorder_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneorderitem',
            name='rain_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='droneorderitem',
            name='wind_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
