# Generated by Django 4.2.4 on 2025-09-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_droneorder_dronebatteryorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dronebatteryorderitem',
            old_name='order',
            new_name='drone_order',
        ),
        migrations.RenameField(
            model_name='dronebatteryorderitem',
            old_name='mode',
            new_name='drone_service',
        ),
        migrations.AlterUniqueTogether(
            name='dronebatteryorderitem',
            unique_together={('drone_order', 'drone_service')},
        ),
    ]
