# Generated by Django 4.2.4 on 2025-09-14 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DroneOrder',
            new_name='DroneBatteryOrder',
        ),
        migrations.RenameModel(
            old_name='DroneOrderItem',
            new_name='DroneBatteryOrderItem',
        ),
        migrations.RenameModel(
            old_name='DroneMode',
            new_name='DroneService',
        ),
    ]
